### ISSUE TITLE
Pip install does not fetch the latest version

### ISSUE THREAD

**Issue by nobe4** [froala/django-froala-editor#27]
##### Expected behavior.
Install the latest `django-froala-editor` version.

##### Actual behavior.
Install the `django-froala-editor` version 2.0.1.

##### Steps to reproduce the problem.
(using virtualenvwrapper to ease the test)

    mktmpenv
    pip search froala
    pip install django-froala-editor

The version `2.0.1` gets installed, even though the `2.3.2` is [present on the pypi website](https://pypi.python.org/pypi/django-froala-editor) and the pip search shows a `2.1.0` version.

![screen shot 2016-06-13 at 10 40 41](https://cloud.githubusercontent.com/assets/2452791/16003188/5604ead0-3153-11e6-8a8d-437679759c1a.png)

##### OS.
OS X Yosemity 10.10.5
pip version 8.1.2
python 2.7

#### EDIT
Following [this conversation](http://stackoverflow.com/a/37787000/2558252) I've been able to install the latest version of the editor, but the issue remains.

**Comment by devunt** [comment]
In a version [2.0.1](https://pypi.python.org/pypi/django-froala-editor/2.0.1), `django-froala-editor-2.0.1.tar.gz` is exists in the downloads section.
However, since [2.0.2](https://pypi.python.org/pypi/django-froala-editor/2.0.2), there is no downloadable links.

I guess `python setup.py sdist` is missing in the process of publishing a package into pypi.

@stefanneculai Can you check it?

**Comment by devunt** [comment]
Since `pip install django-froala-editor` is installing 2.0.1, in order to use the latest version of the package people should run `pip install git+https://github.com/froala/django-froala-editor` instead.

**Comment by nobe4** [comment]
That's what I ended up doing, thanks 👍
